CREATE DATABASE Friends;
USE Friends;

CREATE TABLE EMP2(
id INT NOT NULL,
PRIMARY KEY (id),
salary INT DEFAULT 20000
);

INSERT INTO EMP2 (id) VALUES (102);

SELECT* FROM EMP2;

CREATE DATABASE IF NOT EXISTS JIO2;
USE JIO2;
CREATE TABLE JIO(
id INT PRIMARY KEY,
city VARCHAR(50),
age INT,
CONSTRAINT age_Check CHECK (age>=18 AND city="Ranchi")
);
INSERT INTO JIO
(id,city,age)
VALUES
(2,"Ranchi",19);
SELECT * FROM JIO;